CAR-36 в проект добавлена возможность использования PostCSS.
carousel-without-a-horse/ticket-to-ride pull request #15
Opened 2023-06-12 09:14 UTC by Surovev

### Какую задачу решаем
в проект добавлена возможность использования PostCSS.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-13 17:30 UTC, aleksanderlamkov approved these changes

2023-06-13 19:28 UTC, NikitaFilippovAleks approved these changes

2023-06-14 18:26 UTC, NikitaFilippovAleks approved these changes

2023-06-14 18:27 UTC, NikitaFilippovAleks requested changes

2023-06-14 18:27 UTC, NikitaFilippovAleks commented on packages/client/.eslintrc
> +          ]
тут правильно табуляция стоит?  Массив и объект вроде не доллжны быть на одном уровне

2023-06-14 18:36 UTC, Surovev commented on packages/client/.eslintrc
> +          ]
ты прав, уехало

2023-06-14 18:40 UTC, Surovev commented on packages/client/.eslintrc
> +          ]
поправил

2023-06-14 18:42 UTC, NikitaFilippovAleks approved these changes

2023-06-14 19:37 UTC, merged