[CAR-31] PWA
carousel-without-a-horse/ticket-to-ride pull request #16
Opened 2023-06-12 16:03 UTC by aleksanderlamkov

### Какую задачу решаем
[CAR-31](https://linear.app/carousel-without-a-horse/issue/CAR-31/dobavit-service-workers-prilozhenie-dolzhno-popadat-v-kesh-pri-pervoj)

### Скриншоты
[Успешно работающий ServiceWorker](https://tppr.me/QYcIY)
[Файлы для корректной работы ServiceWorker, появляющиеся в директории dist после сборки](https://tppr.me/3p35z)

2023-06-12 18:04 UTC, NikitaFilippovAleks approved these changes

2023-06-14 06:26 UTC, MilkaDurilka commented on packages/client/vite.config.ts
> +    VitePWA({ registerType: 'autoUpdate', devOptions: { enabled: true } }),
Должно ли `devOptions: { enabled: true } }` быть и для продакшен сборки?

2023-06-14 07:09 UTC, practicum-maxim-zyryanov requested changes
Решение прекрасное, но для реальных проектов. В задаче же требуется научиться писать Service Worker самостоятельно, поэтому отправляю на доработку.

2023-06-14 08:02 UTC, aleksanderlamkov commented
> Решение прекрасное, но для реальных проектов. В задаче же требуется научиться писать Service Worker самостоятельно, поэтому отправляю на доработку.

@practicum-maxim-zyryanov, привет, я не согласен с тем, что здесь требуется доработка.

В задаче сказано:
"Добавить Service Workers. Приложение должно попадать в кеш при первой загрузке и после этого загружаться без интернета (не только элементы входа и пользовательские настройки, но и сама игра)."

Ключевые моменты — "добавить" и "приложение должно... и далее по списку". Всё это реализовано.

До реализации через библиотеку я писал конфигурацию самостоятельно и обсудил с командой свое решение. Процитирую самого себя:
```
Для создания PWA версии приложения вижу 2 пути:

1. Прописывать вручную все генерируемые после билда чанки для их кеширования. Для этого нужно задавать им удобночитаемые имена при конфигурировании билд-версии Vite через rollupOptions, плюс когда появятся новые чанки (когда будут готовы другие части приложения), нужно будет и их не забыть добавить. Ну и в целом кода для настройки serviceWorker будет много.

2. Всё сделать через плагин к Vite, который автоматом подхватит все чанки и слепит из них PWA. Единственный момент - нужен Vite посовременнее. 

Если никто не против, идем по пути наименьшего сопротивления, обновляю Vite до свежей версии и ставлю плагин для PWA и закрываю задачку.
```

Подитожу:
Я не вижу рациональным написание конфигурации sw с нуля, ибо мы на старте выбрали современный многофункциональный сборщик Vite, в экосистеме которого есть библиотека, решающая нашу задачу.

2023-06-14 08:04 UTC, aleksanderlamkov commented on packages/client/vite.config.ts
> +    VitePWA({ registerType: 'autoUpdate', devOptions: { enabled: true } }),
На продакшен версию это никак не влияет. Эта опция нужна исключительно для того, чтобы хоть как-то сымитировать работу SW в дев-режиме.

2023-06-14 08:41 UTC, aleksanderlamkov commented
> Решение прекрасное, но для реальных проектов. В задаче же требуется научиться писать Service Worker самостоятельно, поэтому отправляю на доработку.

@practicum-maxim-zyryanov я перечитал теорию курса ещё раз.

<img width="759" alt="image" src="https://github.com/carousel-without-a-horse/ticket-to-ride/assets/69209610/68cc3922-8543-44d4-b3b0-0a201d7371b0">

Теория явно призывает нас найти способ изящнее, чем костылить пути до статики вручную:

<img width="542" alt="image" src="https://github.com/carousel-without-a-horse/ticket-to-ride/assets/69209610/e8cb968b-8968-4c0a-87f2-035b66fdbacf">

2023-06-14 09:37 UTC, aleksanderlamkov commented
> Решение прекрасное, но для реальных проектов. В задаче же требуется научиться писать Service Worker самостоятельно, поэтому отправляю на доработку.

@practicum-maxim-zyryanov если всё таки "для галочки" в проекте нужна ручная настройка SW, то я её добавил, а библиотеку `vite-plugin-pwa` убрал. Если наша дискуссия придет к тому, что решим, что можно таки вернуть как было, с решением через библиотеку, то откачу последний коммит.

2023-06-15 13:54 UTC, practicum-maxim-zyryanov commented
Немного предыстории... мне нравится идея использовать готовую библиотеку, но здесь студентов многое заставляют писать с нуля, поэтому получив пул-реквест закинул вопрос в команду сопровождения, можно студентам сейчас сдавать такое решение или отправлять на доработку... на что получил ответ "отправлять на доработку", это действительно недоработка бэклога, требование явно пропишут, если уже не прописали.

@aleksanderlamkov, поэтому спасибо, что решение доработал

К слову, мне нравится твоя идея, с откатом решения... команда и правда может оставить это решение в отдельной ветке, а в проекте использовать более лаконичное, плюс вам легче будет дружить готовое решение с другими технологиями, чем самописное. Вот это требования курса не запрещают.

2023-06-15 14:15 UTC, practicum-maxim-zyryanov approved these changes

2023-06-15 16:20 UTC, aleksanderlamkov commented
> 

Спасибо за объяснение. Всё понимаю, регламент курса требует написание студентами кода самостоятельно там, где это возможно, как с SW.

2023-06-15 16:28 UTC, merged