[CAR-34] MobX + Tanstack Query
carousel-without-a-horse/ticket-to-ride pull request #17
Opened 2023-06-13 12:36 UTC by MilkaDurilka

### Какую задачу решаем
[CAR-34](https://linear.app/carousel-without-a-horse/issue/CAR-34/dobavit-hranilishe)
MobX - используется для хранения UI состояние приложение
Tanstack Query - используется для работы с данными с сервера (кеширование, пагинация, бесконечная загрузка)
Добавлена краткая  документация по работе со state в `docs/state.md`

MobX на данный момент хранит:
- тему
- язык

Tanstack Query прикручен на странице форума. Работает бесконечная загрузка (данные замоканы на сервере) и кеширование результатов запросов.

Файлы с локализацией хранятся в `/src/shared/lib/i18n/locales`. В этом ПР локализован только раздел форума.

### Скриншоты/видяшка (если есть)

https://github.com/carousel-without-a-horse/ticket-to-ride/assets/12884728/e87b6661-9477-49ad-997f-ce61a502312e

https://github.com/carousel-without-a-horse/ticket-to-ride/assets/12884728/5413f414-a039-4152-820e-0187ed72cd07

2023-06-13 17:51 UTC, aleksanderlamkov commented on docs/state.jpg
Очень крутая идея со схемой!

2023-06-13 17:51 UTC, aleksanderlamkov commented on packages/client/src/entities/theme/api.ts
> +  item: async ({ id }) => {
Может назовём `getItem`? Будет чуть более информативнее. А то метод назван, словно геттер.

2023-06-13 17:51 UTC, aleksanderlamkov commented on packages/client/src/app/providers/withTheme.tsx
> +            colorBgContainer: isDarkMode ? '#000' : '#fff',
Предлагаю привести все hex-значения к единому шестисимвольному стилю в верхнем регистре.

2023-06-13 17:51 UTC, aleksanderlamkov commented on packages/client/src/entities/theme/types.ts
> +}
Смущает название поля `theme` в типах, относящихся к теме. Может лучше `name` назвать?

2023-06-13 17:51 UTC, aleksanderlamkov commented on packages/client/src/features/QueryTable/ui.tsx
> +          : t('table.loader.finish')}
Лучше добавить табуляции для этих строк, вложенный тернарник будет лучше читаться.

2023-06-13 17:51 UTC, aleksanderlamkov commented on packages/client/src/pages/ForumPage/ui/Themes/index.tsx
>    const [selectedItem, setSelectedItem] = useState<string[]>([])
Кажется, что либо данные не должны быть массивом, либо сущность называться должна не `item`, а `items`, то есть во множественном числе.

2023-06-13 19:26 UTC, NikitaFilippovAleks approved these changes

2023-06-14 22:58 UTC, marilisok approved these changes

2023-06-15 20:30 UTC, Olegas requested changes

2023-06-15 20:30 UTC, Olegas commented on packages/client/src/entities/theme/api.ts
> +    return await httpService
1. Не надо делать return await - это не имеет смысла. Достаточно просто вернуть наружу тот Promise, который пытаемся дождаться
2. В этой функции вообще async/await не нужен - можно смело убирать

2023-06-15 20:30 UTC, Olegas commented on packages/client/src/entities/theme/api.ts
> +    return await httpService
Та же история что и в функции выше - async не нужен, return await не имеет смысла.

2023-06-15 20:30 UTC, Olegas commented on packages/client/src/features/LangSelect/ui.tsx
> +    void i18n.changeLanguage(lang)
Для чего здесь void? Что это дает?

2023-06-15 20:30 UTC, Olegas commented on packages/client/src/features/QueryTable/ui.tsx
> +  }, [refetch])
А вот этот useCallback точно тут нужен? Почему нельзя сделать onClick={refetch} просто?

2023-06-15 20:30 UTC, Olegas commented on packages/client/src/shared/hooks/useTranslateOutside/index.ts
> +export const useTranslateOutside = <T>(getData: () => T): T => {
Если я правильно понял, то этот хук позволяет обновить что-то, зависящее от локализации, при смене языка. Если да, то название не очень понятное. Я бы предложил что-то вроде useTranslationRefresh или что-то в этом духе

2023-06-16 05:51 UTC, MilkaDurilka commented on packages/client/src/shared/hooks/useTranslateOutside/index.ts
> +export const useTranslateOutside = <T>(getData: () => T): T => {
Согласна, переименовала!

2023-06-16 05:51 UTC, MilkaDurilka commented on packages/client/src/features/QueryTable/ui.tsx
> +  }, [refetch])
Потому что `refetch` ожидает параметр `options`, который в данном случае не нужен. Если сделать `onClick={refetch}`, то в `options` попадет `event`

2023-06-16 05:51 UTC, MilkaDurilka commented on packages/client/src/features/LangSelect/ui.tsx
> +    void i18n.changeLanguage(lang)
По правилу eslint: [no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md#ignorevoid)

2023-06-16 05:51 UTC, MilkaDurilka commented on packages/client/src/entities/theme/api.ts
> +    return await httpService
Спасибо, убрала!

2023-06-16 05:51 UTC, MilkaDurilka commented on packages/client/src/entities/theme/api.ts
> +    return await httpService
Спасибо, убрала!

2023-06-16 09:12 UTC, Olegas approved these changes
Спасибо, все супер! 🔥

2023-06-16 09:34 UTC, merged