[CAR-30] Проработать визуальную часть игры.
carousel-without-a-horse/ticket-to-ride pull request #18
Opened 2023-06-14 19:43 UTC by NikitaFilippovAleks

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-17 07:45 UTC, MilkaDurilka requested changes
В основном замечания по импортам и расположению модулей. Если много исправлений для этого пр, то можешь создать отдельную задачу на рефакторинг и прикрепить ее сюда.

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/entities/Game/utils/renderRoute.ts
> +  ctx.beginPath()
DRY.  Можно вынести рисование объектов в функции. 
```
drawRail(rail1)
...
drawRail(rail2)
```
а потом объединить вызовы функций drawRail и данные rail1 и rail2 в `drawRails`.
Аналогично со шпалами drawSleepers

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/entities/Game/utils/renderRoute.ts
> +import { gameSetup } from '@/widgets/Game/data/gameSetup'
@aleksanderlamkov 
По [fsd](https://feature-sliced.design/ru/docs/reference/layers#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D1%81%D0%BB%D0%BE%D1%91%D0%B2) только из shared можно импортить в entities. 
`Модуль в слайсе может импортировать другие слайсы только в том случае, если они расположены на слоях строго ниже.`
<img width="208" alt="image" src="https://github.com/carousel-without-a-horse/ticket-to-ride/assets/12884728/0452783a-d26c-4fde-ac67-da571a0c2da9">

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/shared/ui/Game/Button/ui.tsx
> +import { colors } from '@/app/providers/colors'
тоже нарушение [fsd](https://feature-sliced.design/ru/docs/reference/layers#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D1%81%D0%BB%D0%BE%D1%91%D0%B2) импортов

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/shared/ui/Game/Button/ui.tsx
> +    width: 130,
если у button есть файл со стилями почему бы не вынести эти стили туда? В остальных компонентах аналогично

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/shared/ui/Game/Button/styles.module.pcss
> +  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
`box-shadow` повторяется в проекте, можно ли его вынести в миксины?

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/shared/ui/Game/Card/ui.tsx
> +import { useState } from 'react'
нужно везде проверить  соответствие импортов [fsd](https://feature-sliced.design/ru/docs/reference/layers#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D1%81%D0%BB%D0%BE%D1%91%D0%B2)  и подумать куда лучше вынести из shared

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/shared/ui/Game/Card/ui.tsx
> +  const borderWidth = isSelected ? 4 : 1
4 и 1 - магические числа, вынеси в константы, чтобы понимать их смысл по названию

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/widgets/Game/data/colorCards.ts
> +  black: {
может просто ...colors.game

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/app/providers/colors.ts
>      black: '#1E1E1E',
colors.ts не совсем провайдер, я бы предложила хранить цвета в app/styles/variables.pcss в `:root`

2023-06-17 07:45 UTC, MilkaDurilka commented on packages/client/src/widgets/Game/ui/Draft/ui.tsx
> +      {renderOpenCards()}
Почему не компонентами `<OpenCards />` и `<Buttons />`?

2023-06-17 14:31 UTC, NikitaFilippovAleks commented on packages/client/src/entities/Game/utils/renderRoute.ts
> +  ctx.beginPath()
тут по сути просто рисование линии происходит. Создал функцию drawLines для отрисовки

2023-06-17 14:35 UTC, NikitaFilippovAleks commented on packages/client/src/entities/Game/utils/renderRoute.ts
> +import { gameSetup } from '@/widgets/Game/data/gameSetup'
перенес данные игры в entities/Game/data после обсуждения

2023-06-17 18:25 UTC, NikitaFilippovAleks commented on packages/client/src/shared/ui/Game/Button/ui.tsx
> +import { colors } from '@/app/providers/colors'
вынес colors в shared/constants

2023-06-17 18:26 UTC, NikitaFilippovAleks commented on packages/client/src/shared/ui/Game/Button/ui.tsx
> +    width: 130,
вынес все в styles.module.pcss

2023-06-17 18:26 UTC, NikitaFilippovAleks commented on packages/client/src/shared/ui/Game/Button/styles.module.pcss
> +  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
добавил миксины

2023-06-17 18:27 UTC, NikitaFilippovAleks commented on packages/client/src/shared/ui/Game/Card/ui.tsx
> +import { useState } from 'react'
данные игры вынесены в entities,  colors в shared

2023-06-17 18:28 UTC, NikitaFilippovAleks commented on packages/client/src/shared/ui/Game/Card/ui.tsx
> +  const borderWidth = isSelected ? 4 : 1
вынес

2023-06-17 18:29 UTC, NikitaFilippovAleks commented on packages/client/src/widgets/Game/data/colorCards.ts
> +  black: {
тут нельзя, это отдельная сущность. Есть например карта rainbow, у которой цвет black

2023-06-17 18:30 UTC, NikitaFilippovAleks commented on packages/client/src/app/providers/colors.ts
>      black: '#1E1E1E',
вынес

2023-06-17 18:32 UTC, NikitaFilippovAleks commented on packages/client/src/widgets/Game/ui/Draft/ui.tsx
> +      {renderOpenCards()}
решил, что они не достойны отдельных компонентов) У них своей логики нет, все будет в Draft происходить

2023-06-17 19:32 UTC, MilkaDurilka approved these changes

2023-06-17 19:32 UTC, MilkaDurilka commented on packages/client/src/entities/Game/data/routes.ts
> +// import type { TGameColors } from '@/app/providers/colors'
забыл комментарий

2023-06-17 19:35 UTC, NikitaFilippovAleks commented on packages/client/src/entities/Game/data/routes.ts
> +// import type { TGameColors } from '@/app/providers/colors'
поправил

2023-06-18 15:45 UTC, Olegas commented
А как я могу увидеть такую же картинку, как в заглавном комментарии? Зашел вот сюда: https://deploy-preview-18--lucky-palmier-326077.netlify.app/ - увидеть игру не смог

2023-06-18 16:50 UTC, NikitaFilippovAleks commented
> А как я могу увидеть такую же картинку, как в заглавном комментарии? Зашел вот сюда: https://deploy-preview-18--lucky-palmier-326077.netlify.app/ - увидеть игру не смог

Локально можно запустит и перейти по роуту game. На нетлифай почему то не дает по роутам переходить, если руками их вбивать

2023-06-18 17:21 UTC, Olegas approved these changes
Есть вопрос по коду (не блокирует приемку). Возможно забыли убрать элемент, или он просто оставлен на будущее (написал комментарий в коде).

2023-06-18 17:21 UTC, Olegas commented on packages/client/src/shared/ui/Game/RouteCard/ui.tsx
> +        <canvas className={styles.canvas}></canvas>
А вот этот canvas - не лишний? На нем ничего не рисуется...

2023-06-18 17:31 UTC, NikitaFilippovAleks commented on packages/client/src/shared/ui/Game/RouteCard/ui.tsx
> +        <canvas className={styles.canvas}></canvas>
этот элемент на будущее. Потом в нем будет небольшая отрисовка

2023-06-18 17:34 UTC, merged