[CAR-29] start/end of game
carousel-without-a-horse/ticket-to-ride pull request #21
Opened 2023-06-16 12:54 UTC by Surovev

### Какую задачу решаем
Реализация начала и завершения игры

Сделана верстка, добавление игроков в стейт и редиректы, все кроме редиректа в конце игры

### Скриншоты/видяшка (если есть)
[Страница завершения игры](https://scrnli.com/files/mujAL8nJOkG85L)
[Страница начала игры](https://scrnli.com/files/tRrT99ZG5kg1c3)
[Страница начала игры](https://scrnli.com/files/gbxvNiJS2kFtud)

### TBD (если есть)

2023-06-16 18:58 UTC, NikitaFilippovAleks requested changes
1. Думаю режим игры должен стоять по умолчанию с последующей возможностью выбора
2. Персонажам надо бы добавить поле name и назвать по русски с большой буквы
3. Зачем на странице начать игру кнопка назад? У нас ведь есть верхнее меню
4. Зачем на экране завершения кнопка выйти?

2023-06-16 18:58 UTC, NikitaFilippovAleks commented on packages/client/src/pages/EndGamePage/data.ts
> +export const dataSource: TDataSource = [
Это мок данные? Если да, то можно комментарий оставить типа
TODO: заменить мок данные на динамические

2023-06-16 18:58 UTC, NikitaFilippovAleks commented on packages/client/src/pages/EndGamePage/index.tsx
> +import { useNavigate } from 'react-router-dom'
у нас договоренность по проекту, что ui находится в файлах ui.tsx. А index.ts мы используем для реэуспорта из директории

2023-06-16 18:58 UTC, NikitaFilippovAleks commented on packages/client/src/pages/StartGamePage/data.ts
> +export const playersOptions: object[] = []
тут получается не игроки, а персонажи. Думаю лучше переименовать в charactersOptions. И тип расписать вместо просто object, чтобы нагляднее было. Тип также можно вынести в файл types  в той же директории

2023-06-16 18:58 UTC, NikitaFilippovAleks commented on packages/client/src/pages/StartGamePage/index.tsx
> +  const onChangePlayer = (value: string) => {
onChangeCharacter

2023-06-16 18:58 UTC, NikitaFilippovAleks commented on packages/client/src/pages/StartGamePage/index.tsx
> +          options={[{ label: 'Тестовый режим', value: 'test' }]} // доработается, как только появятся режимы
Думаю лучше назвать режим "Против компьютера"

2023-06-16 18:58 UTC, NikitaFilippovAleks commented on packages/client/src/pages/StartGamePage/index.tsx
> +        <h3>Выберете свой персонаж</h3>
Тут наверно своего персонажа)

2023-06-17 08:36 UTC, MilkaDurilka commented on packages/client/src/pages/EndGamePage/data.ts
> +export const dataSource: TDataSource = [
и прикрепить номер задачи, в которой это будет сделано

2023-06-17 08:36 UTC, MilkaDurilka commented on packages/client/src/pages/EndGamePage/index.tsx
> +const cardStyle = {
ты же подключил pcss, почему решил не выносить стили в отдельный файл?

2023-06-17 08:36 UTC, MilkaDurilka commented on packages/client/src/shared/store/store.ts
> +import { characters } from '@/widgets/Game/data/characters'
этот импорт нарушает правила [FSD](https://feature-sliced.design/ru/docs/reference/layers#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D1%81%D0%BB%D0%BE%D1%91%D0%B2) 
`Модуль в слайсе может импортировать другие слайсы только в том случае, если они расположены на слоях строго ниже.`
<img width="200" alt="image" src="https://github.com/carousel-without-a-horse/ticket-to-ride/assets/12884728/060433ae-438d-46ad-b371-d7e794834cb4">

2023-06-17 08:36 UTC, MilkaDurilka commented on packages/client/src/shared/store/store.ts
> +      const players = Object.keys(characters as object)
`as`  в случаях, когда этого можно избежать лучше не использовать. Лучше добавить проверки типов

2023-06-17 08:36 UTC, MilkaDurilka commented on packages/client/src/shared/store/store.ts
> +    handlePlayerChoice: function (value: TPlayer) {
Не совсем понятно из названия, что должен делать этот метод. Метод должен выполнять только одно действие, например, установку  `currentPlayer`. Тогда `opponentPlayer` - это вычисляемое значение, аналогично `isDarkMode` будет вычисляться автоматически в зависимости от `currentPlayer`

2023-06-17 08:36 UTC, MilkaDurilka commented on packages/client/src/widgets/Game/data/characters.ts
> +//   IconBanana,
комменты не комитим

2023-06-17 10:09 UTC, Surovev commented on packages/client/src/pages/EndGamePage/data.ts
> +export const dataSource: TDataSource = [
@MilkaDurilka  а если этой задачи еще нет? Создать?

2023-06-17 12:10 UTC, MilkaDurilka commented on packages/client/src/pages/EndGamePage/data.ts
> +export const dataSource: TDataSource = [
Да, конечно

2023-06-17 14:14 UTC, Surovev commented on packages/client/src/pages/EndGamePage/index.tsx
> +const cardStyle = {
Вроде решили стили для Antd хранить в том же файле где они используются

2023-06-17 15:14 UTC, Surovev commented on packages/client/src/pages/EndGamePage/index.tsx
> +const cardStyle = {
@MilkaDurilka @NikitaFilippovAleks Все пофиксил кроме стилей. Еще вынес файл с игроками в константы, переделаю его как только Никитин пр будет готов, потому как я от туда список персонажей и дернул. Тогда же сделаю название персонажей на русском.

2023-06-17 19:36 UTC, MilkaDurilka commented on packages/client/src/pages/EndGamePage/index.tsx
> +const cardStyle = {
Никита в своем [ПР](https://github.com/carousel-without-a-horse/ticket-to-ride/pull/18) стили все вынес в файлы, стало намного лаконичней и чище. Мне кажется по возможности надо стремиться к единству

2023-06-17 19:42 UTC, MilkaDurilka commented on packages/client/src/shared/store/store.ts
> +    currentCharacter: null as TCharacters,
Маша в своем [ПР](https://github.com/carousel-without-a-horse/ticket-to-ride/pull/22/files#diff-c44d42a24c55029c879f0d7e252c4bc1dbfd9e7f9cba558b30d80ae400c8ad8c) создала отдельный стор для user, может тут тоже лучше вынести в стор для игры.

2023-06-17 19:42 UTC, MilkaDurilka commented on packages/client/src/shared/store/store.ts
> +      this.currentCharacter = value
все равно все что ниже 26 строки непонятно почему в этом методе.

2023-06-18 14:52 UTC, Surovev commented on packages/client/src/shared/store/store.ts
> +      this.currentCharacter = value
Так это временное решение выбора противника, в задаче CAR-38 сделаю нормально, коммент об этом тоже есть

2023-06-18 14:52 UTC, Surovev commented on packages/client/src/shared/store/store.ts
> +    currentCharacter: null as TCharacters,
Согласен, вынес

2023-06-18 14:55 UTC, Surovev commented on packages/client/src/pages/EndGamePage/index.tsx
> +const cardStyle = {
Я согласен, но у Никиты вынесены стили не для библиотечных компонентов, а у меня стили только для них и есть на данный момент. Либо я что-то не понимаю, если так - сильно палками не бейте пожалуйста)

2023-06-18 17:44 UTC, Surovev commented on packages/client/src/pages/EndGamePage/data.ts
> +export const dataSource: TDataSource = [
Сделал

2023-06-18 17:45 UTC, Surovev commented on packages/client/src/pages/EndGamePage/index.tsx
> +import { useNavigate } from 'react-router-dom'
Вынес

2023-06-18 17:45 UTC, Surovev commented on packages/client/src/pages/StartGamePage/data.ts
> +export const playersOptions: object[] = []
Сделал

2023-06-18 17:45 UTC, Surovev commented on packages/client/src/pages/StartGamePage/index.tsx
> +  const onChangePlayer = (value: string) => {
переименовал

2023-06-18 17:45 UTC, Surovev commented on packages/client/src/pages/StartGamePage/index.tsx
> +          options={[{ label: 'Тестовый режим', value: 'test' }]} // доработается, как только появятся режимы
Согласен, сделал

2023-06-18 17:45 UTC, Surovev commented on packages/client/src/pages/StartGamePage/index.tsx
> +        <h3>Выберете свой персонаж</h3>
упс)

2023-06-18 17:47 UTC, Surovev commented on packages/client/src/shared/store/store.ts
> +import { characters } from '@/widgets/Game/data/characters'
Вынес, но как ток смерджу все будет как у Никиты, тк я его файл использую

2023-06-18 17:47 UTC, Surovev commented on packages/client/src/shared/store/store.ts
> +      const players = Object.keys(characters as object)
Исправил

2023-06-18 17:49 UTC, Surovev commented on packages/client/src/shared/store/store.ts
> +    handlePlayerChoice: function (value: TPlayer) {
Я полагаю, в дальнейшем его можно будет выбрать, по этому пока сделал так

2023-06-18 17:49 UTC, Surovev commented on packages/client/src/widgets/Game/data/characters.ts
> +//   IconBanana,
Убрал

2023-06-18 17:55 UTC, NikitaFilippovAleks commented on packages/client/src/pages/EndGamePage/index.tsx
> +import { useNavigate } from 'react-router-dom'
немного не так. В index файле вообще не должно быть никакого tsx. Только реэкспорты того, что находится в текущей директории. Получается тут должно быть export { EndGamePage } from './ui' (еще могут реэкспортироваться типы, если они где-то снаружи нужны). А уже в самом ui.tsx будет вся разметка и логика

2023-06-18 17:57 UTC, Surovev commented on packages/client/src/pages/EndGamePage/index.tsx
> +import { useNavigate } from 'react-router-dom'
у меня почему-то ломается сборка если я делаю только export { EndGamePage } from './ui в индекс файле , я не смог понять почему именно, и сделал так, если ты сможешь подсказать я буду очень признателен

2023-06-18 18:05 UTC, NikitaFilippovAleks commented on packages/client/src/pages/EndGamePage/index.tsx
> +import { useNavigate } from 'react-router-dom'
ты прав, видимо для страниц и роутера так не настроили

2023-06-18 18:08 UTC, NikitaFilippovAleks approved these changes

2023-06-19 11:25 UTC, MilkaDurilka commented on packages/client/src/shared/store/store.ts
> +import { characters } from '@/widgets/Game/data/characters'
Главное чтобы после мержа ничего не сломалось и соответcтвовало fsd

2023-06-19 11:31 UTC, Surovev commented on packages/client/src/shared/store/store.ts
> +import { characters } from '@/widgets/Game/data/characters'
Само собой

2023-06-19 11:31 UTC, MilkaDurilka commented on packages/client/src/pages/EndGamePage/index.tsx
> +const cardStyle = {
я просто проустила момент, когда решали не трогать стили для анта. Почему такие ограничения были введены? Какую проблему решает разделение стилей?

2023-06-19 11:37 UTC, Surovev commented on packages/client/src/pages/EndGamePage/index.tsx
> +const cardStyle = {
Как мы вчера выяснили с Кириллом, antd подружить с postCss если и реально, но надо очень подпрыгнуть. Я сегодня планирую как раз изучить подробнее этот момент и предложить возможные варианты хранения и использования этих стилей.

2023-06-19 17:22 UTC, practicum-maxim-zyryanov approved these changes
Approve, прекрасная работа, и отдельное спасибо за грамотное использование todo

2023-06-19 17:22 UTC, practicum-maxim-zyryanov commented on packages/client/src/app/providers/colors.ts
В пул-реквесте не встречается упоминание добавленных цветов, файлик похоже из другой задачи.

2023-06-20 12:09 UTC, Surovev commented on packages/client/src/app/providers/colors.ts
Это я из соседнего пр тащил нужные для моего пр изменения, после мерджа их там нет)

2023-06-20 12:16 UTC, merged