[CAR-32]Authorization + HOC
carousel-without-a-horse/ticket-to-ride pull request #22
Opened 2023-06-17 11:31 UTC by marilisok

### Какую задачу решаем
Реализовать логику авторизации + авторизация должна проверяться через отдельно написанный HOC
### Скриншоты/видяшка (если есть)

Uploading Запись экрана 2023-06-17 в 14.28.17.mov…

2023-06-17 11:56 UTC, aleksanderlamkov commented on packages/client/src/shared/hocs/withAuth.tsx
> +      return <></>
Лучше `return null`.

2023-06-17 11:56 UTC, aleksanderlamkov commented on packages/client/src/shared/store/userStore.ts
> +}
Давай `string | null` вынесем в `type TLogin = string | null`.

2023-06-17 11:56 UTC, aleksanderlamkov commented on packages/client/src/widgets/Header/ui.tsx
> +      item => item.key !== ROUTES.signUp && item.key !== ROUTES.signIn
Предлагаю деструктуризировать `key`, чуть короче будет.

2023-06-17 11:56 UTC, aleksanderlamkov commented on packages/client/src/widgets/Header/ui.tsx
> +      item => item.key === ROUTES.signUp || item.key === ROUTES.signIn
Предлагаю деструктуризировать `key`, чуть короче будет.

2023-06-17 11:56 UTC, aleksanderlamkov commented on packages/client/src/widgets/SignUpForm/ui.tsx
> +          .signUp(user)
Давай оптимизируем, переименуем в snake_case (как в апи) имена для полей first_name и second_name и напишем подобное:
```
const user = { ...data }

delete user.passwordRepeat

authServices.signUp(...user)
```

2023-06-17 15:02 UTC, marilisok commented on packages/client/src/widgets/Header/ui.tsx
> +      item => item.key !== ROUTES.signUp && item.key !== ROUTES.signIn
Поправила

2023-06-17 15:02 UTC, marilisok commented on packages/client/src/widgets/Header/ui.tsx
> +      item => item.key === ROUTES.signUp || item.key === ROUTES.signIn
Поправила

2023-06-17 15:02 UTC, marilisok commented on packages/client/src/shared/store/userStore.ts
> +}
Поправила

2023-06-17 15:02 UTC, marilisok commented on packages/client/src/shared/hocs/withAuth.tsx
> +      return <></>
Поправила

2023-06-17 15:03 UTC, marilisok commented on packages/client/src/widgets/SignUpForm/ui.tsx
> +          .signUp(user)
Обсудили, что из-за логики валидации не будем это поправлять (строка 35)
<img width="631" alt="Снимок экрана 2023-06-17 в 18 03 35" src="https://github.com/carousel-without-a-horse/ticket-to-ride/assets/31723865/c16baf4e-be02-49ba-ac1d-dc9323dc3785">

2023-06-17 15:13 UTC, aleksanderlamkov approved these changes

2023-06-17 17:28 UTC, Olegas requested changes
Есть вопросы/замечания по коду

2023-06-17 17:28 UTC, Olegas commented on packages/client/src/pages/GamePage/index.tsx
> +const AboutPage = withAuth(() => {
Тут что-то не то с названием компонента. Видимо что-то скопипастили и забыли переименовать

2023-06-17 17:28 UTC, Olegas commented on packages/client/src/shared/hocs/withAuth.tsx
> +      localStorage.getItem(LOCAL_STORAGE_KEYS.userLogin) &&
localStorage.getItem(LOCAL_STORAGE_KEYS.userLogin) - уже выше вынесено в переменную localStorageUserLogin, не надо дважды начитывать

2023-06-17 17:28 UTC, Olegas commented on packages/client/src/shared/services/userServices/index.ts
> +httpService.defaults.baseURL = 'https://ya-praktikum.tech/api/v2'
В сервисе авторизации уже выставили базовый URL. А зачем это делать в сервисах? Почему в httpService сразу не указать?

2023-06-17 17:28 UTC, Olegas commented on packages/client/src/widgets/SignInForm/ui.tsx
> +            localStorage.setItem(LOCAL_STORAGE_KEYS.userLogin, data.login)
Для чего нужно что-то запоминать в local storage?

2023-06-18 16:06 UTC, marilisok commented on packages/client/src/pages/GamePage/index.tsx
> +const AboutPage = withAuth(() => {
Поправила

2023-06-18 16:06 UTC, marilisok commented on packages/client/src/shared/hocs/withAuth.tsx
> +      localStorage.getItem(LOCAL_STORAGE_KEYS.userLogin) &&
Поправила

2023-06-18 16:06 UTC, marilisok commented on packages/client/src/shared/services/userServices/index.ts
> +httpService.defaults.baseURL = 'https://ya-praktikum.tech/api/v2'
Поправила

2023-06-18 16:07 UTC, marilisok commented on packages/client/src/widgets/SignInForm/ui.tsx
> +            localStorage.setItem(LOCAL_STORAGE_KEYS.userLogin, data.login)
Для того, чтобы если авторизованный пользователь закроет/откроет/перезагрузит страницу, он оставался в системе

2023-06-18 17:27 UTC, Olegas commented on packages/client/src/widgets/SignInForm/ui.tsx
> +            localStorage.setItem(LOCAL_STORAGE_KEYS.userLogin, data.login)
@marilisok А что если сессия "протухла" или пользователь например почистил cookie и уже не авторизован, но приложение по прежнему считает что все хорошо? Как бороться с такой проблемой?

2023-06-18 18:00 UTC, MilkaDurilka requested changes

2023-06-18 18:00 UTC, MilkaDurilka commented on packages/client/src/shared/services/httpService.ts
> -  baseURL: `http://localhost:${__SERVER_PORT__}`,
Разве это не сломает работу запросов форума?

2023-06-18 18:05 UTC, Olegas commented on packages/client/src/shared/services/httpService.ts
> -  baseURL: `http://localhost:${__SERVER_PORT__}`,
Возможно тогда стоит именно в сервисе, отвечающем за форум, поменять адрес. Потому что для всех остальных задач нужен другой адрес и вроде как не дело выставлять его заново в каждом сервисе.

2023-06-18 18:18 UTC, marilisok commented on packages/client/src/widgets/SignInForm/ui.tsx
> +            localStorage.setItem(LOCAL_STORAGE_KEYS.userLogin, data.login)
@Olegas Не совсем поняла вопрос какое отношение сессии и куки имеют к local storage?

2023-06-18 18:23 UTC, MilkaDurilka commented on packages/client/src/shared/services/httpService.ts
> -  baseURL: `http://localhost:${__SERVER_PORT__}`,
Логично, просто обращаю внимание, что это изменение влечёт за собой поломку другой части. 
Когда нам впервые показали беклог в 5 спринте, мы думали, что весь бек будем делать сами. Из-за этого у нас был один baseUrl с localhost

2023-06-18 18:31 UTC, Olegas commented on packages/client/src/widgets/SignInForm/ui.tsx
> +            localStorage.setItem(LOCAL_STORAGE_KEYS.userLogin, data.login)
Авторизация - это cookie. Предположим сценарий
1. Пользователь авторизовался, получил cookie
2. В local storage записали что он авторизован
3. Дальше случается одно из двух например: пользователь почистил куки или сервис решил сбросить авторизацию (например пользователь зашел в Яндекс и выбрал там "прервать все сессии"
4. Авторизации у вас больше нет, но в local storage записано что пользователь авторизован. Приложение пытается работать но не может. 

Что у вас произойдет в этой ситуации?

2023-06-19 11:36 UTC, MilkaDurilka commented on packages/client/src/shared/services/httpService.ts
> -  baseURL: `http://localhost:${__SERVER_PORT__}`,
@Olegas 
Может лучше в следующей задаче вынести запросы к 'https://ya-praktikum.tech/api/v2' в packages/server - будет BFF. Далее будет легче заменить на свое решение. А с клиента все запросы посылать на http://localhost:${__SERVER_PORT__}

2023-06-20 18:37 UTC, MilkaDurilka commented on packages/client/src/pages/AboutPage/index.tsx
> +const AboutPage = withAuth(() => {
Маш, ты рассматривала вариант добавлять withAuth в packages/client/src/app/router/router.tsx?
Возможно в этом файле будет нагляднее отслеживать страницы под авторизацией

2023-06-25 17:40 UTC, marilisok commented on packages/client/src/shared/services/httpService.ts
> -  baseURL: `http://localhost:${__SERVER_PORT__}`,
@Olegas я все поправила, полностью переписав логику

2023-06-25 19:57 UTC, marilisok commented on packages/client/src/widgets/SignInForm/ui.tsx
> +            localStorage.setItem(LOCAL_STORAGE_KEYS.userLogin, data.login)
Полностью переписала логику и удалила localStorage

2023-06-26 19:42 UTC, Olegas approved these changes
Супер! 🔥

2023-06-26 21:11 UTC, merged

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/app/index.tsx
> +  const routes = useRoutes(user ? privateRouter : publicRouter)
Можно сразу return

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/app/providers/withUserIdentification.tsx
> +      userStore.fetchUser().then(console.log).catch(console.log)
при загрузке страницы уходит два get запроса fetchUser.

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/app/router/router.tsx
> -        path: ROUTES.signIn,
Если пользователь авторизован и у него была открытка вкладка с signIn/signUp, то после обновления страницы его перекинет на 404, а лучше перебросить его на главную.

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/pages/ProfilePage/ui/ProfileForm/ui.tsx
> +import { error } from '@/shared/utils/notification/intex'
опечатка в названии файла index.

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/pages/ProfilePage/ui/ProfileForm/ui.tsx
> +import type { AxiosError } from 'axios'
мы обернули axios в httpService, на случай если в дальнейшем нужно будет заменить на другое решение. Лучше все зависимости от axios держать там. И AxiosError переименовать например в THttpServiceError

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/pages/ProfilePage/ui/ProfileForm/ui.tsx
> +        const res = err.response?.data as TError
Для чего используется TError? Лучше проверки на наличие полей проводить в явном виде. Можно добавить утилит  hasKey(data, 'reason')

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/shared/services/authServices/types.ts
> +  fetchUser: () => Promise<TUser>
fetchUser сейчас возвращает не TUser, а { data: TUser }.

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/shared/store/user/userStore.ts
> +import authServices from 'src/shared/services/authServices'
@/shared/services/authServices

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/shared/store/user/userStore.ts
> +import type { AxiosError } from 'axios'
зависимость от axios вынести в httpService

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/shared/store/user/userStore.ts
> +import type { TUser } from '@/pages/ProfilePage/ui/ProfileForm/type'
В `shared` нельзя импортировать из  `pages`.
Я бы порекомендовала вынести работу с user в папку `entities`. 
user одна из главных сущностей в проекте.

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/shared/store/user/userStore.ts
> +      if ((error as AxiosError).isAxiosError) {
Можно убрать все as и заменить проверку в if на error instanceof AxiosError.

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/shared/store/user/userStore.ts
> +      this.user = response
response.data ?

2023-06-27 09:03 UTC, MilkaDurilka commented on packages/client/src/shared/types/error.ts
> +export type TError = {
Не понятно, что за ошибка