CAR-40: Вынесла стили
carousel-without-a-horse/ticket-to-ride pull request #23
Opened 2023-06-20 19:32 UTC by MilkaDurilka

### Какую задачу решаем
Вынесла стили в styles.module.pcss

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-20 20:04 UTC, NikitaFilippovAleks requested changes

2023-06-20 20:04 UTC, NikitaFilippovAleks commented on packages/client/src/app/layouts/BaseLayout/styles.module.pcss
> +}
в этом файле и некоторых последующих нет пустой строки в конце файла - обозначается красным значком. Некоторые старые системы могут некорректно читать такие файлы, плюс при просмотре файла в консоли например через cat последняя строка может отображаться некорректно. Мне об этом говорил проверяющий в прошлом модуле. Не знаю как в веб шторме, но в vscode есть настройка, которая автоматически добавляет пустую строку в редактируемый файл

2023-06-20 20:04 UTC, NikitaFilippovAleks commented on packages/client/src/app/providers/withTheme.tsx
> +          colorBgLayout: isDarkMode ? '#222222' : '#3993DD',
может лучше вынести эти цвета в colors и брать оттуда?

2023-06-21 13:45 UTC, MilkaDurilka commented on packages/client/src/app/providers/withTheme.tsx
> +          colorBgLayout: isDarkMode ? '#222222' : '#3993DD',
Спасибо, ты прав! Взяла цвета из colors

2023-06-21 13:47 UTC, MilkaDurilka commented on packages/client/src/app/layouts/BaseLayout/styles.module.pcss
> +}
Спасибо! Исправила. Добавила в  .editorconfig правило insert_final_newline.
Так же добавил stylelint.

2023-06-21 18:58 UTC, NikitaFilippovAleks approved these changes

2023-06-21 19:01 UTC, merged