Feature/car 38
carousel-without-a-horse/ticket-to-ride pull request #26
Opened 2023-07-07 11:22 UTC by Surovev

### Какую задачу решаем
добавлена логика начала и завершения игры, защищены переходы на страницы игры и завершения игры через адресную строку.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-07 12:22 UTC, aleksanderlamkov commented on packages/client/src/pages/EndGamePage/ui.tsx
> +  }, [gameStore, navigate])
Сущность `gameStore` — объект, следовательно срабатывать этот `useEffect` будет при изменении любого поля внутри этого объекта. Если так и задумано, то ок, но мне кажется, что лучше будет деструктуризировать заранее `gameStatus` и `players`, затем использовать их в массиве зависимостей `useEffect` и во внутреннем коде.

2023-07-07 12:22 UTC, aleksanderlamkov commented on packages/client/src/pages/EndGamePage/ui.tsx
> +        ).points
Очень сложно воспринимается такая связка из фигурных скобок и многоточия. Может как-нибудь можно повысить читаемость этого куска кода? 

Я бы сделал так:
```
const { points } = players[key as TPlayersKey]
```

P. S. players - деструктуризированное поле вне useEffect.

2023-07-07 12:22 UTC, aleksanderlamkov commented on packages/client/src/pages/EndGamePage/ui.tsx
> +      result.sort((a, b) => (a.scores < b.scores ? -1 : 1))
1. Можно упростить, выражение в функции внутри sort до `(a, b) => a.scores - b.scores`.
2. Тут точно мутация оригинального массива `result` ничего не сломает? Я бы лучше сделал промежуточную переменную `sortedPlayers`, далее оперировал бы ей.

2023-07-09 11:05 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +  }, [gameStore, navigate])
Согласен, лишние рендеры ни к чему, поправил

2023-07-09 11:06 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +        ).points
Прямо так не сработало, но на одну ступень я упростил)

2023-07-09 11:08 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +      result.sort((a, b) => (a.scores < b.scores ? -1 : 1))
Про упростить согласен, про мутацию - не вижу ничего плохого в этом, имхо в двух переменных сложнее запутаться, чем в одной. Оно отлично работает к тому же. Нашел кстати косяк, с номером занятого места, пока смотрел как лучше, и его тоже поправил)

2023-07-09 14:20 UTC, aleksanderlamkov commented on packages/client/src/pages/EndGamePage/ui.tsx
> +  return gameStore.gameStatus === 'endGame' ? (
Лучше сделать так:

```
if (gameStore.gameStatus !== 'endGame') {
  return null
}

return основная_разметка
```

2023-07-09 14:20 UTC, aleksanderlamkov commented on packages/client/src/pages/GamePage/index.tsx
> +  return gameStore.gameStatus === 'gameInProcess' ? (
Лучше сделать так:

```
if (gameStore.gameStatus !== 'gameInProcess') {
  return null
}

return основная_разметка
```

2023-07-09 14:31 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +  return gameStore.gameStatus === 'endGame' ? (
Согласен, так значительно красивее

2023-07-09 14:32 UTC, Surovev commented on packages/client/src/pages/GamePage/index.tsx
> +  return gameStore.gameStatus === 'gameInProcess' ? (
Соответственно, поправил

2023-07-09 14:32 UTC, aleksanderlamkov approved these changes

2023-07-09 16:30 UTC, IvanPeleshok commented on packages/client/src/pages/EndGamePage/ui.tsx
> +    }
Предлагаю отделять логические блоки пустым абзацем, иначе это выглядит, как каша

2023-07-09 16:31 UTC, IvanPeleshok commented on packages/client/src/pages/EndGamePage/ui.tsx
> +        } else if (item.user === 'currentPlayer') {
Если есть if return, то else ни к чему, достаточно использовать снова if 
Так код выглядит чище и читаемее

2023-07-09 16:32 UTC, IvanPeleshok commented on packages/client/src/pages/EndGamePage/ui.tsx
> +        })
Не хватает отступов, выглядит, как каша

2023-07-09 16:34 UTC, IvanPeleshok commented on packages/client/src/pages/EndGamePage/ui.tsx
> +      Object.keys(users).forEach((key, i) => {
Не стоит сокращать имена переменных, код мы пишем, в первую очередь, для других людей, это не олимпиадное программирование (такие нагруженные бизнесовые куски кода должны быть читаемыми, аккуратными и, по-хорошему, покрыты тестами (в лучших практиках, выносят в утилиты)

2023-07-09 16:36 UTC, IvanPeleshok commented on packages/client/src/pages/EndGamePage/ui.tsx
> +  }
Не хватает отступа

2023-07-09 16:37 UTC, IvanPeleshok commented on packages/client/src/pages/EndGamePage/ui.tsx
> +        onOk={() => {
Рекомендация: инлайн колбеки плохи из-за производительности и читаемости (в дальнешейшем предлагаю почитать про их оптимизацию)

2023-07-09 16:38 UTC, IvanPeleshok commented on packages/client/src/pages/EndGamePage/ui.tsx
> +          gameStore.setGameStatus('noGame')
noGame вынести в константу, т.к это плюс к масштабируемости (переиспользуемость) и дебагингу

2023-07-09 16:41 UTC, IvanPeleshok commented on packages/client/src/pages/GamePage/index.tsx
> +      <Button // Костыль, что бы попадать на страницу конца игры, коллбеки следует перенести в логику, которая сработает после завершения игры.
Если комментировать, то не в той же строке, что и компонент, обычно это делают выше над компонентом или другой сущностью

2023-07-09 16:43 UTC, IvanPeleshok commented on packages/client/src/shared/store/game/gameStore.ts
> +    console.log(this.gameStatus)
От логирования избавляемся во время PR, чтобы не тащить код отладки в dev
Для этого лучше использовать devtools для стора

2023-07-09 16:46 UTC, IvanPeleshok commented on packages/client/src/pages/EndGamePage/ui.tsx
> +    const toResultConverter = (users: TPlayers): TDataSource => {
Давай вынесем этот код в отдельный модуль (файл) и постараемся написать с отступами и т.д
Предлагаю не бояться писать больше переменных, если где-то можно сократить
На производительности это не скажется практически, но человеку, который будет читать ваш код - будет приятно и понятно, плюсом будет то, что вы сами не запутаетесь и не допустите глупых ошибок
Как бонус: можно покрыть тестами

2023-07-09 16:46 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-13 10:55 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +    }
Согласен, но линтер не везде позволяет это делать

2023-07-13 10:56 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +        } else if (item.user === 'currentPlayer') {
Не заметил, прправил)

2023-07-13 10:56 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +        })
Сделал, где это возможно

2023-07-13 10:58 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +      Object.keys(users).forEach((key, i) => {
На мой взгляд довольно читаемо, к тому же там ключи обьекта и итерируются, не вижу ничего сокращенного в названии ключа ключом, но поправил)

2023-07-13 10:59 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +          gameStore.setGameStatus('noGame')
Вынес в константы все статусы игры

2023-07-13 10:59 UTC, Surovev commented on packages/client/src/pages/GamePage/index.tsx
> +      <Button // Костыль, что бы попадать на страницу конца игры, коллбеки следует перенести в логику, которая сработает после завершения игры.
перенес

2023-07-13 11:00 UTC, Surovev commented on packages/client/src/shared/store/game/gameStore.ts
> +    console.log(this.gameStatus)
ок, убрал, постараюсь дальше использовать тулзы

2023-07-13 11:00 UTC, Surovev commented on packages/client/src/pages/EndGamePage/ui.tsx
> +    const toResultConverter = (users: TPlayers): TDataSource => {
сделал, но без тестов

2023-07-13 11:14 UTC, IvanPeleshok approved these changes

2023-07-15 08:30 UTC, merged