[CAR-41] SRR
carousel-without-a-horse/ticket-to-ride pull request #27
Opened 2023-07-07 12:31 UTC by MilkaDurilka

### Какую задачу решаем
Настроить Express для Server Side Rendering 

### Скриншоты/видяшка (если есть)
Получение верстки страницы с сервера:
<img width="1411" alt="image" src="https://github.com/carousel-without-a-horse/ticket-to-ride/assets/12884728/511640b1-0b9a-4ad8-b97c-bf57094e19a3">

### TBD (если есть)

2023-07-07 12:44 UTC, aleksanderlamkov commented on packages/server/app/utils/developmentServer.ts
> +      appHtml = appHtml.replace(STUBS_IN_TEMPLATE.style, style)
Может заменить на `const` и продолжить чейнинг с третьим вызовом `replace`?

2023-07-07 12:44 UTC, aleksanderlamkov commented on packages/client/src/shared/services/authServices/index.ts
А эти изменения точно необходимы? В `packages/server/shared/repository/yandexAPIRepository.ts` ведь есть кусочек с `v2`. Или я не туда смотрю?

2023-07-07 12:47 UTC, Surovev commented on packages/client/src/app/router/forum.tsx
> +// const Forum = withCommonWrappers(() => import('@/pages/ForumPage'))
вроде ж не коммитим комменты, в router.tsx тоже есть

2023-07-07 14:00 UTC, MilkaDurilka commented on packages/client/src/shared/services/authServices/index.ts
необходимы, так как запросы с `api/v2` - уходят на сервер яндекса([см. код](https://github.com/carousel-without-a-horse/ticket-to-ride/pull/27/files#diff-e9ed60945d0e1dc784b5df2cff17f4fc37373c19cebc84ad33cf43ef12de03afR20))

но у нас есть уже ручки, например, для форума. Они не должны уходить на сервер яндекса, там не используется`v2`. ([см. код](https://github.com/carousel-without-a-horse/ticket-to-ride/pull/27/files#diff-e9ed60945d0e1dc784b5df2cff17f4fc37373c19cebc84ad33cf43ef12de03afR31))

2023-07-07 14:05 UTC, MilkaDurilka commented on packages/client/src/app/router/forum.tsx
> +// const Forum = withCommonWrappers(() => import('@/pages/ForumPage'))
Спасибо, что заметил. Я пока оставила эти комментарии, так как планирую у ментора узнать нюансы использования SSR совместно с Suspense. Удалю перед мержем.

2023-07-07 14:06 UTC, MilkaDurilka commented on packages/server/app/utils/developmentServer.ts
> +      appHtml = appHtml.replace(STUBS_IN_TEMPLATE.style, style)
спасибо, исправила!

2023-07-07 14:30 UTC, aleksanderlamkov approved these changes

2023-07-08 14:02 UTC, Olegas requested changes
На мой взгляд практика делать bind-методы и глушить линтер только ради того, что бы использовать деструктуризацию - странная и вредная. Возможно я не вижу какой-то пользы тут.
Объясните пожалуйста, зачем так делать? В чем идея?

2023-07-08 14:02 UTC, Olegas commented on packages/client/src/ssr.tsx
> +  // eslint-disable-next-line @typescript-eslint/unbound-method
А зачем делать в сторе bind что бы затем тут глушить eslint? Почему не обратиться userStore.setUser(user)?

2023-07-08 14:02 UTC, Olegas commented on packages/client/src/app/router/router.tsx
> +// const Game = withCommonWrappers(() => import('@/pages/GamePage'))
Давайте не будем оставлять закоментированный код

2023-07-08 14:02 UTC, Olegas commented on packages/client/src/app/providers/withInitialState.tsx
> +  const { setUser } = userStore
Решительно не понимаю чем так плохо писать userStore.setUser(...).
Так плохо что лучше глушить линтер.

2023-07-08 15:19 UTC, MilkaDurilka commented on packages/client/src/ssr.tsx
> +  // eslint-disable-next-line @typescript-eslint/unbound-method
Спасибо за ревью, Олег. Исправила)

Задача оказалась достаточно сложная, поэтому видимо не хватило мысле-топлива для обхода глушилки eslint. В процессе решения задачи возникло несколько проблем:
1) с миксинами для postcss. Не подхватывался путь до миксинов при рендере на сервере. Поэтому поправила mixinDir в конфиге.
2) Стили для antd не извлекались на сервере. Сейчас это делают функции createCache и extractStyle. 
Делала по инструкции с [ant.design](https://ant.design/docs/react/customize-theme#server-side-render-ssr).
Там порекомендовали использовать `@ant-design/static-style-extract`. Но из-за различий версий `@ant-design/cssinjs`, которые использует библиотека `antd` и `@ant-design/static-style-extract` стили не извлекались. На расследование этого тоже ушло много времени :) 
3) Редактор react-quill не ренедерится на сервере, так как использует document. Он вставляется только на клиенте после загрузки dom.
4) Пока остался вопрос как быть с динамическими импортами при ssr, пока пришлось от них отказаться. Не нашла подробного примера как использовать renderToPipeableStream :(

В остальной части помогли вебинары. Спасибо

2023-07-08 20:12 UTC, Olegas requested changes
Заметил еще одну важную проблему.
Вот здесь: https://github.com/carousel-without-a-horse/ticket-to-ride/blob/d932d77d00be5fb6621894f2505f4a8a236d9e64/packages/client/src/shared/store/user/userStore.ts#L50
Получается у вас на все приложение ровно один экземпляр UserStore.
Пока у каждого пользователя был свой экзепляр в его браузере все было хорошо.
Но теперь, когда у вас есть SSR, у вас (условно) вечноживущее приложение на сервере, которое импортирует файлы из client.
Получается что UserStore будет один, по сути глобальный. Один на весь SSR-сервер. И могут быть ситуации когда запрос одного пользователя может перетереть данные другого. Как следствие пользователь может получить страницу не со своими данными, например.
Нужно избегать глобальных переменных.

2023-07-10 07:34 UTC, MilkaDurilka commented
> Заметил еще одну важную проблему. Вот здесь:
> 
> https://github.com/carousel-without-a-horse/ticket-to-ride/blob/d932d77d00be5fb6621894f2505f4a8a236d9e64/packages/client/src/shared/store/user/userStore.ts#L50
> 
> 
> Получается у вас на все приложение ровно один экземпляр UserStore.
> Пока у каждого пользователя был свой экзепляр в его браузере все было хорошо.
> Но теперь, когда у вас есть SSR, у вас (условно) вечноживущее приложение на сервере, которое импортирует файлы из client.
> Получается что UserStore будет один, по сути глобальный. Один на весь SSR-сервер. И могут быть ситуации когда запрос одного пользователя может перетереть данные другого. Как следствие пользователь может получить страницу не со своими данными, например.
> Нужно избегать глобальных переменных.

Спасибо, @Olegas, что подсветили это. Я планировала вынести стор в следующей задаче про ssr.
В 7 спринте есть 2 задачи про ssr:
1) Настроить Express для Server Side Rendering (без стора, просто отдавать React-страничку)
2) Настроить стор и Router в SSR.

Часть второй задачи про роутер я реализовала в первой, чтобы не было проблем с дальнейшей разработкой у других членов команды. Так как если пользователь уже авторизован, а мы показываем ему страницу с авторизацией, то повторно пользователь не проходил авторизацию с ошибкой: "User already in system". Возможно это можно было обойти не добавляя роутер, но мне так показалось проще.

Так как сейчас для ssr после вашего комментария я добавила отдельный стор, можно ли считать, что обе задачи выполнены? Или я что-то упускаю?

2023-07-10 15:11 UTC, Olegas approved these changes
👍 Спасибо, все ок.

2023-07-10 15:37 UTC, merged