CAR-45 - Добавить ещё одно WEB API
carousel-without-a-horse/ticket-to-ride pull request #29
Opened 2023-07-17 18:30 UTC by NikitaFilippovAleks

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-18 09:27 UTC, MilkaDurilka requested changes

2023-07-18 09:27 UTC, MilkaDurilka commented on packages/client/src/pages/GamePage/index.tsx
> +  useUserAttention({
Расскажи, что делает этот хук? Лучше добавить описание в сам компонент.

2023-07-18 09:27 UTC, MilkaDurilka commented on packages/client/src/pages/GamePage/index.tsx
> +import { notification } from 'antd'
У нас есть папка /src/shared/utils/notification. Предлагаю вынести зависимость от antd  туда и импортировать из той папки.

2023-07-18 09:27 UTC, MilkaDurilka commented on packages/client/src/pages/GamePage/index.tsx
> +        description: 'Не уходите далеко, игра в самом разгаре!',
У нас 2 языка в проекте, давайте во всех новых задачах стараться добавлять переводы.
Переводы хранятся в `packages/client/src/shared/lib/i18n/locales`.
Пример реализации можно посмотреть в разделе форума и шапке.

2023-07-18 09:27 UTC, MilkaDurilka commented on packages/client/src/shared/utils/useUserAttention.ts
> +import { useCallback, useEffect, useRef, useState } from 'react'
Все хуки храним в папке `packages/client/src/shared/hooks`

2023-07-18 09:27 UTC, MilkaDurilka commented on packages/client/src/shared/utils/useUserAttention.ts
> +// function handleVisibilityChange(onHide: () => void, onBack: () => void) {
Остался комментарий и console.log ниже. Задача еще в драфте?

2023-07-18 09:27 UTC, MilkaDurilka commented on packages/client/src/shared/utils/useUserAttention.ts
> +type TProps = {
типы выносим в файл types.ts

2023-07-18 09:27 UTC, MilkaDurilka commented on packages/client/src/shared/utils/useUserAttention.ts
> +  useEffect(() => {
Если правильно понимаю, то подписка на `visibilitychange` должна происходить при моунте компонента, а отписка при анмаунте. Давай создадим два хука: `useMount` и `useUnmount` в папке `packages/client/src/shared/hooks` и используем здесь.
Ты можешь найти примеры реализации здесь: https://github.com/streamich/react-use/tree/master/src

2023-07-18 09:27 UTC, MilkaDurilka commented on packages/client/src/shared/utils/useUserAttention.ts
> +      if (!isVisibilityListenerAdded) {
Уверен, что нужен `!` знак?

2023-07-18 09:47 UTC, NikitaFilippovAleks commented on packages/client/src/pages/GamePage/index.tsx
> +import { notification } from 'antd'
вынес

2023-07-18 09:54 UTC, NikitaFilippovAleks commented on packages/client/src/pages/GamePage/index.tsx
> +        description: 'Не уходите далеко, игра в самом разгаре!',
добавил локализацию

2023-07-18 09:58 UTC, NikitaFilippovAleks commented on packages/client/src/shared/utils/useUserAttention.ts
> +import { useCallback, useEffect, useRef, useState } from 'react'
перенес

2023-07-18 09:59 UTC, NikitaFilippovAleks commented on packages/client/src/shared/utils/useUserAttention.ts
> +// function handleVisibilityChange(onHide: () => void, onBack: () => void) {
была в драфте, убрал console.log

2023-07-18 09:59 UTC, NikitaFilippovAleks commented on packages/client/src/shared/utils/useUserAttention.ts
> +type TProps = {
вынес

2023-07-18 10:13 UTC, NikitaFilippovAleks commented on packages/client/src/shared/utils/useUserAttention.ts
> +  useEffect(() => {
тут получается onBack в handleVisibilityChange зависит от absenceTime, поэтому поместил absenceTime в зависимости. То есть слушатель не толко при маунте добавляется, не понял как по-другому реализовать

2023-07-18 10:14 UTC, NikitaFilippovAleks commented on packages/client/src/shared/utils/useUserAttention.ts
> +      if (!isVisibilityListenerAdded) {
это условие тут не нужно, убрал

2023-07-18 10:16 UTC, NikitaFilippovAleks commented on packages/client/src/pages/GamePage/index.tsx
> +  useUserAttention({
добавил коммент к хуку

2023-07-18 10:21 UTC, aleksanderlamkov approved these changes

2023-07-18 10:43 UTC, MilkaDurilka approved these changes

2023-07-18 10:43 UTC, MilkaDurilka commented on packages/client/src/pages/GamePage/index.tsx
> +import { useNotification } from '@/shared/utils/notification/intex'
intex надо переимновать в index. Это явно опечатка(

2023-07-18 19:42 UTC, IvanPeleshok approved these changes

2023-07-19 16:04 UTC, NikitaFilippovAleks commented on packages/client/src/pages/GamePage/index.tsx
> +import { useNotification } from '@/shared/utils/notification/intex'
поправил

2023-07-19 16:06 UTC, merged