Feature/car 19
carousel-without-a-horse/ticket-to-ride pull request #5
Opened 2023-05-31 13:33 UTC by aleksanderlamkov

### Какую задачу решаем
[CAR-19](https://linear.app/carousel-without-a-horse/issue/CAR-19/vyorstka-stranicy-logina-logika-avtorizacii)

### Скриншоты
[Пункт меню "Войти" в шапке](https://tppr.me/ELz2v)
[Изначальный вид страницы и формы авторизации](https://tppr.me/8ONTV)
[Попытка войти без ввода данных в требуемые поля](https://tppr.me/kXY2R)
[Отображение вводимого пароля при клике на кнопку с иконкой глаза](https://tppr.me/Z6v4b)
[Отправка POST запроса с данными на несуществующий на момент PR URL](https://tppr.me/BQ3b5)

2023-05-31 19:07 UTC, marilisok approved these changes

2023-06-01 07:51 UTC, MilkaDurilka requested changes

2023-06-01 07:51 UTC, MilkaDurilka commented on packages/client/src/shared/services/authServices.ts
> +import axios from 'axios'
Предлагаю вынести axios в httpService. 
Это даст нам следующие преимущества:
- Легче будет заменить, если потребуется
- Общие настройки в одном месте(установка токена или interceptors)

2023-06-01 07:51 UTC, MilkaDurilka commented on packages/client/src/widgets/SignInForm/ui.tsx
> +  const navigate = useNavigate()
nitpick: navigate и ROUTES не используются

2023-06-01 07:57 UTC, aleksanderlamkov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +  const navigate = useNavigate()
Оставил специально, в т. ч. закомментированный код по использованию этих двух сущностей ниже. После верстки страницы регистрации всё это будет использоваться.

2023-06-01 07:57 UTC, MilkaDurilka commented on packages/client/src/shared/services/types.d.ts
> +export type TSignInSent = {
Почему файл имеет расширение d.ts? Насколько понимаю, если мы используем export, то `d` писать не нужно.

2023-06-01 08:08 UTC, aleksanderlamkov commented on packages/client/src/shared/services/types.d.ts
> +export type TSignInSent = {
Привычка. Поменяю расширение. Спасибо.

2023-06-01 11:07 UTC, practicum-maxim-zyryanov approved these changes
Approve, нормальное решение задачи, критичных вопросов сейчас не возникает, но ряд комментариев на будущее стоит учесть 😄

2023-06-01 11:07 UTC, practicum-maxim-zyryanov commented on .prettierrc
> -  "width": 50
**[Рекомендация]**
Не критично сейчас, но критично на реальных проектах. Эта настройка не относится к решению задачи, и хорошая практика выносить такие глобальные изменения в отдельную задачу. К примеру, если сейчас задача застрянет на ревью, это вынудит остальных ждать мерджа или вносить аналогичные изменения у себя.

2023-06-01 11:07 UTC, practicum-maxim-zyryanov commented on packages/client/package.json
> +    "axios": "^1.4.0",
Здесь ситуация аналогичная. Зависимость от axios необходима не только для этой задачи, а для всего проекта, поэтому можно провести это изменение вместе с .prettierrc под какой-нибудь задачей начального сетапа проекта.

2023-06-01 11:07 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/GuidePage/index.tsx
> +          >
В виду изменения стиля кода здесь и далее можем встретить элементы рефакторинга, что также к задаче не относится и отвлекает от сути. И вновь подобная правка нормально смотрелась бы в задаче начального сетапа, т.к. изменили настройку стиля, и естественно поправили по новым правилам все файлы. Сейчас же мы решаем задачу по форме, но лезем в файлы, в которые по задаче нам лезть не требовалось. Потенциально это несёт больше конфликтов, которые потребуется решать при мердже. Потенциально это и возможность случайно занести ошибку, которую затем будет отчасти сложно найти, т.к. никто не подумает, что привнесена она вообще не связанной с ней задачей.

2023-06-01 11:07 UTC, practicum-maxim-zyryanov commented on packages/client/src/shared/services/types.d.ts
> +  signIn: (data: TSignInSent) => Promise<unknown>
Действительно ли unknown?

2023-06-01 11:07 UTC, practicum-maxim-zyryanov commented on packages/client/src/shared/ui/Form/items/InputItem/ui.tsx
Возможно что-то упускаю из вида, но зачем здесь деструктурировать чуть ли не весь props? Понимаю `inputType` используется предварительно, но в форме можно ведь было использовать:
```
<Form.Item
      required={props.required}
```

2023-06-01 11:07 UTC, practicum-maxim-zyryanov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +        rules={[{ required: true, message: 'Пожалуйста, введите ваш логин' }]}
Хорошее решение здесь воспользоваться готовой библиотекой для валидации

2023-06-01 11:07 UTC, practicum-maxim-zyryanov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +        }}
Совсем не критично, но на несколько моментов обратил бы внимание в целях профилактики:
1. При тестировании функционала нажимаешь на ссылку и она не работает. Смотришь в код и видно, что по очевидным причинам. Но возможно стоило бы её на время скрыть, и на реальном проекте избавиться на время от лишнего вопроса тестировщика.
2. Код в комментарии. Здесь легко предположить почему он оставлен, но код в комментарии всегда вызывает вопросы. Если есть возможность, лучше его не оставлять. А если и оставлять, то писать причину, почему эти строки закомментированы, чтобы другие разработчики и ты со временем могли понять актуален ли комментарий.
3. Ранее объявлен `onSubmit`, и возможно здесь стоило придерживаться унифицированного подхода и объявить тот же `onSignUp`

2023-06-01 11:15 UTC, aleksanderlamkov commented on packages/client/package.json
> +    "axios": "^1.4.0",
В одной из первоначальных задач по настройке необходимых для проекта библиотек не учли, что может понадобится 'axios', поэтому пришлось добавлять в рамках текущей задачи и ветки.

2023-06-01 11:16 UTC, aleksanderlamkov commented on packages/client/src/shared/services/types.d.ts
> +  signIn: (data: TSignInSent) => Promise<unknown>
Это временно. Всё равно работающего реального эндпоинта у нас пока нет.

2023-06-01 11:16 UTC, practicum-maxim-zyryanov commented
@aleksanderlamkov, рекомендую в команде договориться, настроить linear.app если потребуется, и добавлять в заголовок PR не только номер, но и название задачи, т.к. по номеру различать PR будет сложно, когда их станет больше, а автоматизация работает и при наличии заголовка.

2023-06-01 11:20 UTC, aleksanderlamkov commented on packages/client/src/shared/ui/Form/items/InputItem/ui.tsx
Данный кусок кода написан не мною, я лишь внес корректировки, необходимые для реализации функционала в рамках моей задачи.

Но я также в своих проектах привык наглядно деструктуризировать `props`, а не передавать их напрямую из `props.`. В большинстве ситуаций количество пропсов в компонентах гораздо меньше, плюс необходимо задавать дефолтные значения, поэтому без деструктуризации обойтись сложно.

2023-06-01 11:29 UTC, aleksanderlamkov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +        rules={[{ required: true, message: 'Пожалуйста, введите ваш логин' }]}
Использующаяся под капотом компонента формы библиотека `ant` "изкоробки" имеет валидацию и подключать какой-нибудь `yup` для этой цели уже не имеет смысла.

2023-06-01 11:29 UTC, aleksanderlamkov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +        }}
1. Да, понимаю, на реальном проекте это было бы нехорошо. Но тестировщика у нас нет, а следующей задачей по интеграции страницы регистрации занимаюсь я, поэтому чтобы не забыть соединить страницу авторизации с регистрацией я и оставил эту неработающую кнопку.
2. Комментарии оставлены с той же целью, что и в п. 1. Комментарии в коде реального проекта в принципе никогда не оставляю, ибо нейминг сущностей и типизация должны говорить сами за себя.
3. Да, неудачный нейминг, согласен. Только скорее стоило `onFinish` написать, как это требует библиотека.

2023-06-01 11:34 UTC, aleksanderlamkov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +        rules={[{ required: true, message: 'Пожалуйста, введите ваш логин' }]}
@practicum-maxim-zyryanov беру свои слова назад, yup с ant работает неплохо (https://stackblitz.com/edit/react-97lr5s?file=index.js). Попробую в рамках задачи "валидация форм" сделать интеграцию с yup.

Спасибо.

2023-06-01 11:42 UTC, MilkaDurilka approved these changes

2023-06-01 11:53 UTC, merged