CAR-20 made up the rating page
carousel-without-a-horse/ticket-to-ride pull request #6
Opened 2023-06-01 09:55 UTC by Surovev

### Какую задачу решаем
CAR-20 Верстка страницы лидборда

### Скриншоты/видяшка (если есть)
[тык](https://scrnli.com/files/qKpwh72Ur0p1cL)

2023-06-01 13:04 UTC, aleksanderlamkov commented on packages/client/src/pages/RatingPage/index.tsx
> +    </>
Если внутри `React.Fragment` (`<></>`) содержится лишь один элемент, то оболочку с фрагментом можно убрать.

2023-06-01 13:06 UTC, aleksanderlamkov commented on package-lock.json
Этот файл лишний, стоит убрать. Предположу, что он появился после случайного `npm i`. А т. к. у нас yarn, то и команды другие и файл для фиксации версионности другой - `yarn.lock`.

2023-06-01 15:51 UTC, Surovev commented on packages/client/src/pages/RatingPage/index.tsx
> +    </>
Согласен, затупил, спасибо

2023-06-01 18:58 UTC, MilkaDurilka commented
Почему-то в измененных файлах еще и Сашины изменения из задачи [CAR-19](https://linear.app/carousel-without-a-horse/issue/CAR-19/vyorstka-stranicy-logina-logika-avtorizacii)

2023-06-01 20:25 UTC, aleksanderlamkov approved these changes

2023-06-02 10:41 UTC, Surovev commented
@MilkaDurilka Сашины коммиты подтянулись магическим образом после ребейза на дев. Мы с ним решили, что это ок.

2023-06-05 19:41 UTC, bin-umar requested changes
Привет! Я ревьюер из Я.Практикума.

Оставил небольшие замечания и вопросы, не сильно критичные, но лучше исправить их, поэтому жду фиксов.
Также, шапка задача звучит как добавление лидерборда, а фактически добавляется ещё форма авторизации в не полной форме. Не стоит смешивать задачи если изначально не стоит такая задача.

2023-06-05 19:41 UTC, bin-umar commented on packages/client/src/widgets/SignInForm/ui.tsx
> +const SignInForm = () => {
Проще сделать export рядом:
```suggestion
export const SignInForm = () => {
```

2023-06-05 19:41 UTC, bin-umar commented on packages/client/src/pages/RatingPage/index.tsx
> +        }}
Инлайн стили не очень хорошая практика, тем более у тебя какое-то непонятное вычисление, лучше вывести это в файл со стилями

2023-06-05 19:41 UTC, bin-umar commented on packages/client/src/pages/RatingPage/index.tsx
> +const columns = [
Давай добавим тип и выведем в отдельный файл.

2023-06-05 19:41 UTC, bin-umar commented on packages/client/src/pages/RatingPage/index.tsx
> +const dataSource = [
Тут тоже не хватает типа и надо вывести в отдельный файл. Эти типы потом понадобятся при интеграции с апи.

2023-06-05 19:41 UTC, bin-umar commented on packages/client/src/pages/RatingPage/index.tsx
> +    num: '1',
В чём смысл дублировать num как key? Num не уникальный?

2023-06-05 19:41 UTC, bin-umar commented on packages/client/src/pages/RatingPage/index.tsx
> +    key: 'scores',
Тут тоже не очень понятно зачем дублировать `dataIndex` как `key`, ведь можно ж использовать dataIndex напрямую, а если он не уникальный, то можно добавить индекс
```
   key={dataIndex+i}
```

2023-06-05 19:41 UTC, bin-umar commented on packages/client/src/pages/GuidePage/index.tsx
Настоятельно прощу не добавлять такие бессмысленние изменения относительно конкретной задачи которую даёте в ревью, это усложнять процесс ревью.

2023-06-05 19:41 UTC, bin-umar commented on packages/client/package.json
> +    "axios": "^1.4.0",
Чем вас не устраивал обычный fetch?

2023-06-05 19:41 UTC, bin-umar commented on packages/client/src/widgets/SignInForm/ui.tsx
> +  }
Лучше будет обернуть это в useCallback и добавить правильную обработку событий

2023-06-05 19:48 UTC, bin-umar commented on packages/client/src/pages/RatingPage/index.tsx
> +    key: 'scores',
https://ant.design/components/table#column
<img width="1094" alt="Screenshot 2023-06-05 at 22 48 00" src="https://github.com/carousel-without-a-horse/ticket-to-ride/assets/15624993/d7c6d1ff-dde5-4406-9dfd-edf25121740f">

2023-06-05 19:48 UTC, bin-umar commented on packages/client/src/pages/RatingPage/index.tsx
> +    num: '1',
Вижу что antd требует, можно попробовать указать его через rowKey
<img width="1094" alt="Screenshot 2023-06-05 at 22 46 27" src="https://github.com/carousel-without-a-horse/ticket-to-ride/assets/15624993/4fcd3fc8-40f4-4895-b703-374662116645">

2023-06-05 19:49 UTC, bin-umar commented
@aleksanderlamkov также у тебя таблица вышел за пределами родителя
![Screenshot 2023-06-05 at 22 48 34](https://github.com/carousel-without-a-horse/ticket-to-ride/assets/15624993/27ba17bf-61d0-4c64-b327-3f7f8f455c97)

2023-06-05 19:50 UTC, bin-umar commented on packages/client/package.json
> +    "axios": "^1.4.0",
Не пытаюсь запретить использоваться axios, но мне кажется для ваших задач достаточно будет использовать fetch.

2023-06-05 19:51 UTC, aleksanderlamkov commented
@Surovev не твоя часть кода? Не понимаю, почему мне направляют комментарии некоторые 😄 Твой ведь PR.

2023-06-05 19:53 UTC, aleksanderlamkov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +const SignInForm = () => {
Я всегда придерживался принципа "1 файл = 1 по экспортируемая по умолчанию сущность". Здесь с ребятами решили делать иначе, но принцип "одна главная сущность экспортируется в конце файла" кажется мне более удобным, чем экспортировать сущность сразу после её объявления.

2023-06-05 19:57 UTC, aleksanderlamkov commented on packages/client/package.json
> +    "axios": "^1.4.0",
1. Интерсепторс для авторизации в будущем.
2. Указание базового урла для конкретных инстансов, используемых в конкретных файлах сервисов. 
3. Нет необходимости ручного сериалайза гет-параметров и конкатенирования с урлом в гет-запросах.
4. Нет необходимости обрабатывать респонс json-методом.

Считаю, что с фетчом будет больше костылей, нежели с аксиосом.

2023-06-05 19:58 UTC, aleksanderlamkov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +  }
Преждевременная мемоизация - разве это хорошо? Вопрос уже поднимали с другим ревьюером, однозначного вывода по данной теме нет.

2023-06-05 19:58 UTC, bin-umar commented on packages/client/src/widgets/SignInForm/ui.tsx
> +const SignInForm = () => {
> но принцип "одна главная сущность экспортируется в конце файла"

В таком случае стоит сделать его дефолтным
```ts
export default SignInForm;
```

Нет смысла написать
```ts
export {
    SignInForm
}
```
так как это равнозначно то чему я написал выше.

Такой стиль был в requireJS, где обычные модули не были.

2023-06-05 19:59 UTC, aleksanderlamkov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +  }
И "правильная обработка событий" будет на следующем спринте, когда реализуется апи. Безусловно, это заглушка.

2023-06-05 19:59 UTC, bin-umar commented
> @Surovev не твоя часть кода? Не понимаю, почему мне направляют комментарии некоторые 😄 Твой ведь PR.

@aleksanderlamkov прости, это я ошибься :)

2023-06-05 20:03 UTC, aleksanderlamkov commented on packages/client/src/widgets/SignInForm/ui.tsx
> +const SignInForm = () => {
Я понимаю. Но по причине наличия специфичных ре-экспортов в соседнем индекс файле решили делать из юай-файла импорт именованный. 

Визуально удобнее анализировать файл и не видеть "шума" (а-ля export, длинных дженерик-типов, деструктуризации всего и вся прямо в аргументе и т. д.)

Экспорт в конце файла удобен тем, что можно пролистать файл сразу до конца и увидеть, что из файла "отдаётся" одна сущность - компонент-функция, пусть и именованная.

2023-06-05 21:25 UTC, bin-umar commented on packages/client/src/widgets/SignInForm/ui.tsx
> +const SignInForm = () => {
Это не настолько холиварная тема, сделайте как вам удобнее, up to u.

2023-06-05 21:32 UTC, bin-umar commented on packages/client/package.json
> +    "axios": "^1.4.0",
> Считаю, что с фетчом будет больше костылей, нежели с аксиосом.

Да, согласен. Тут скорее вопрос про размер bundle-а https://bundlephobia.com/package/axios@1.4.0, а не про костыли. И в рамках образовательного проекта можно было попытаться реализовать небольшой сетовой модуль самому, но никто не запрещает использовать axios.

В целом хотел услышать как-раз таки аргументы, и вижу что они у вас есть, лайк!)

2023-06-05 21:36 UTC, bin-umar commented on packages/client/src/widgets/SignInForm/ui.tsx
> +  }
> Однозначного вывода по данной теме нет.

Согласен. useCallback будет действительно полезным если передаются переменные извне (props какой-нибудь например). В данном конкретном случае можно и без него.

2023-06-05 21:37 UTC, bin-umar commented on packages/client/src/widgets/SignInForm/ui.tsx
> +  }
> И "правильная обработка событий" будет на следующем спринте, когда реализуется апи. Безусловно, это заглушка.

Ок, можем пропустить тогда этот коммент.

2023-06-06 12:55 UTC, closed without merging